### ISSUE TITLE
Upgrade to 3.34

### ISSUE THREAD

**Issue by dac73** [tiliado/nuvola-flatpaks#1]
Can you upgrade Runtime to 3.34, 3.32 version crashes on 3.34 (including system) because of mesa 19.2 (and probably changed DRM)

**Comment by jiri-janousek** [comment]
Hello @dac73. Thanks for reporting the issue. I'm going to rebuild unstable flatpaks with 3.34 overnight.  Stable flatpaks will follow unless a regression is found.

**Comment by jiri-janousek** [comment]
Unfortunately, there were quite a few build errors so I need more time to resolve them.

**Comment by dac73** [comment]
No problem, take your time. Thank you for looking into it :+1:

**Comment by jiri-janousek** [comment]
Issues in development builds were finally resolved. Stable builds will follow.

```
 common/adk-files.txt    |   4 ++++
 common/app-files.txt    |   4 ++++
 common/base-files.txt   |   4 ++++
 common/cdk-files.txt    |   4 ++++
 common/demo-files.txt   |   4 ++++
 common/nuvola-files.txt |   4 ++++
 common/python-2.7.json  |  52 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 experimental/cdk.json   |   2 +-
 master/adk.json         |   3 +--
 master/app.json         |   2 +-
 master/base.json        |   5 ++---
 master/cdk.json         | 153 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------
 master/demo.json        |   2 +-
 master/nuvola.json      |   2 +-
 14 files changed, 176 insertions(+), 69 deletions(-)
```

**Comment by jiri-janousek** [comment]
New stable flatpaks have been published. Could you check them?

**Comment by dac73** [comment]
It works like a charm. Thanks a bunch.
